services:
  postgres: 
    image: postgres
    container_name: mypostgres
    ports:
      - 5433:5432 # container:host
    env_file:
      - .env.test

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d tests  -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 

  backend:
    image: mybackend
    container_name: mybackend
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy